# Generated by Django 5.0.4 on 2024-05-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=256)),
                ('Email', models.CharField(max_length=256)),
                ('Message', models.CharField(max_length=256)),
            ],
        ),
    ]
